#Spine Role
---
    
- name: set leaf1 downlink to L3
  nxos_interface:
    interface: "{{ l1_interface }}"
    description: Downlink to leaf1
    mode: layer3
    provider: "{{ provider }}"
    
- name: set leaf1 downlink IP address
  nxos_ip_interface:
    interface: "{{ l1_interface }}"
    version: v4
    state: present
    addr: "{{ fabric_link_subnet }}{{ l1_interface_addr }}"
    mask: "{{ fabric_link_mask }}"
    provider: "{{ provider }}"
    
- name: configure OSPF on downlink
  nxos_interface_ospf:
    interface: "{{ l1_interface }}"
    ospf: underlay-1
    area: 0
    provider: "{{ provider }}"
    
- name: set MAC on downlink to L3
  nxos_config:
    lines: 
      - mac-address 0001.0001.0002
    match: line
    parents: "interface {{ l1_interface }}"
    provider: "{{ provider }}"
    
- name: configure leaf BGP neighbours
  nxos_bgp_neighbor:
    asn: "{{ asn }}"
    neighbor: "{{ loopback_subnet }}{{ hostvars[item]['loopback_addr'] }}"
    remote_as: "{{ asn }}"
    description: "spine {{ item }}"
    update_source: loopback0
    state: present
    provider: "{{ provider }}"
  with_items: "{{ groups['leafswitches'] }}"
  
- name: configure leaf BGP neighbours AF
  nxos_bgp_neighbor_af:
    asn: "{{ asn }}"
    neighbor: "{{ loopback_subnet }}{{ hostvars[item]['loopback_addr'] }}"
    afi: l2vpn
    safi: evpn
    send_community: both
    route_reflector_client: true
    state: present
    provider: "{{ provider }}"
  with_items: "{{ groups['leafswitches'] }}"